import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Provider from './StoreProvider';
import { Toaster } from '@/components/ui/toaster';
import axios from 'axios';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	// const cookieStore = cookies();
	// const result = await axios.get('http://localhost:5555/auth/profile', {
	// 	headers: {
	// 		Cookie: `token=${cookieStore.get('token')?.value}`,
	// 	},
	// 	withCredentials: true,
	// });
	return (
		<Provider>
			<html lang="en">
				<head>
					<script
						dangerouslySetInnerHTML={{
							__html: `	if (
						localStorage.theme === 'dark' ||
						(!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)
					) {
						document.documentElement.classList.add('dark');
					} else {
						document.documentElement.classList.remove('dark');
					}`,
						}}
					/>
				</head>
				<body className={inter.className}>
					<main className="h-full">{children}</main>
					<Toaster />
				</body>
			</html>
		</Provider>
	);
}
