export default [
	{
		title: 'First Post',
		shortDescriptions: 'Short description of the first post.',
		text: 'Content of the first post.',
		author: '',
		image: null,
		viewsCount: 0,
		comments: [],
		tags: [],
	},
	{
		title: 'Second Post',
		shortDescriptions: 'Short description of the second post.',
		text: 'Content of the second post.',
		author: '',
		image: null,
		viewsCount: 0,
		comments: [],
		tags: [],
	},
	{
		title: 'Third Post',
		shortDescriptions: 'Short description of the third post.',
		text: 'Content of the third post.',
		author: '',
		image: null,
		viewsCount: 0,
		comments: [],
		tags: [],
	},
	{
		title: 'Fourth Post',
		shortDescriptions: 'Short description of the fourth post.',
		text: 'Content of the fourth post.',
		author: '',
		image: null,
		viewsCount: 0,
		comments: [],
		tags: [],
	},
	{
		title: 'Fifth Post',
		shortDescriptions: 'Short description of the fifth post.',
		text: 'Content of the fifth post.',
		author: '',
		image: null,
		viewsCount: 0,
		comments: [],
		tags: [],
	},
];
